### PR TITLE
Add task to clean up shared files regularly

### PR DESCRIPTION
**Pull request by mkangia**
https://dimagi.atlassian.net/browse/SC-4051

### CODE REVIEW

**Review by Charl1996 — APPROVED** [review]
Looks good! 

Curious why you didn't opt for a server cron task? 

Just to be clear, I don't have a problem with the task in the code (in fact, it's easier to maintain I think), but just wondering how you thought about it.

**Comment by mkangia** [comment]
Hey @Charl1996 

Ya, good question.

It was definitely the maintainability as you mentioned.
Additionally visibility that the files are removed by having the task in this code instead of the ansible repo, plus, having it easily configurable here via superset config.

But overall,
I would think of log files or such to be cleaned via cron but files generated by the application to be removed by application itself.

**Comment by Charl1996** [comment]
>  files generated by the application to be removed by application itself

That's a good point

**Comment by mkangia** [comment]
A bug in setting up the task, resolved in https://github.com/dimagi/commcare-analytics/pull/91

**Pull request merged**
